# Setup
title: ПУЛС ОД ФРОНТОТ 
url: https://pulsodfrontot.github.io
description: "Блог за тактичка медицина и прва помош"
paginate: 1
paginate_path: "/page:num/"
baseurl: "/"
permalink: pretty

# Open Graph / Social Media
image: /assets/og.png
image_width: 1200
image_height: 630

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Jekyll 4.x compatibility
markdown: kramdown
highlighter: rouge

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - vendor

sass:
  sass_dir: _sass
  style: compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: СЕПТЕМВРИ
  url: https://instagram.com/septembertactical

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Архива
    url: /archive

  - title: СЕПТЕМВРИ
    url: /about
